On success

diff --git a/.github/workflows/WindowsBuild.yml b/.github/workflows/WindowsBuild.yml
--- a/.github/workflows/WindowsBuild.yml
+++ b/.github/workflows/WindowsBuild.yml
@@ -43,5 +43,12 @@ jobs:
       timeout-minutes: 5
       # We still want to print the result if the test fails
       continue-on-error: true
-      run: Games\ExampleGame\Build\x64\${{matrix.build-configuration}}\ExampleGame.exe run_tests
-
+      run:  |
+        Games\ExampleGame\Build\x64\${{matrix.build-configuration}}\ExampleGame.exe run_tests > test_output.txt
+        $exitCode = $LastExitCode
+        Get-Content test_output.txt
+        if ($exitCode -ne 0) {
+            Write-Error "Tests failed with exit code $exitCode"
+            exit $exitCode
+        }
+      
